### PR TITLE
Twig 2 support

### PR DESCRIPTION
**Pull request by sauls**

### CODE REVIEW

**Comment by weaverryan** [comment]
Thank so for this! We should definitely support Twig 2 :). I have 2 questions:

1) what was the reason for the phpunit changes? 

2) could we just use the new way of registering the function? It works in Twig 1 for a long time.

Cheers!

**Comment by sauls** [comment]
1. Well if you build with travis-ci for php 7 and up the default build uses phpunit 6 , and phpunit 6 major change is that now it uses namespaces, so tests should be rewritten to support phpunit 6, so I left the default phpunit 4.8 version to run on all builds from php 5.3 to 7.
2. Well you can but then I guess you need to drop support for 2.3 and support from symfony 2.8 and up.

**Comment by weaverryan** [comment]
1. Yea, I think I need to do some work on this, but since it fixes the tests, let's roll with this for now :).

2. I don't think that's correct: the `Twig_SimpleFunction` has existed since Twig `v1.12.0`, which will work fine even with Symfony 2.3 - as it requires at least Twig `1.23` - https://github.com/symfony/symfony/blob/2.3/composer.json#L24 :).

**Comment by sauls** [comment]
1 . :+1: 
2. ok. I have made a commit leaving only the new way of registering the function.

**Comment by weaverryan** [comment]
Thank you! New release tagged :)

**Pull request merged**
